# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d003b4504cea87ded6b853b590bbdb375de70453f4decc19dc307c2a6069741ea480b46d2754a298f04a9fd800756aa534dc80adfd8d7fdc80a1c195898bb2

test:
  secret_key_base: cd5bf652e5adf7018f8382f2cea478ed73ff17da38483054c3bdee4c55930cd339f63cedaa9a4e356dd54f6f7d3d5b86931b90adf60f7b7653a1132b243af5d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
